# Generated by Django 2.1 on 2018-08-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='fecha',
            new_name='fecha_repo',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='name',
            new_name='name_repo',
        ),
    ]
