# Generated by Django 2.1 on 2018-09-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20180826_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='commits',
            field=models.DateTimeField(null=True),
        ),
    ]
