# Generated by Django 2.1 on 2018-09-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_repository_commits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='commits',
            new_name='update',
        ),
    ]
