# Generated by Django 2.1 on 2018-09-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_repositories_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='avatar_url',
            field=models.URLField(),
        ),
    ]
